# Generated by Django 5.0.6 on 2024-07-03 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashcollector',
            old_name='frozen_at',
            new_name='frozen_since',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='cash_collector',
            new_name='collector',
        ),
        migrations.RemoveField(
            model_name='cashcollector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='collected_amount',
        ),
        migrations.AddField(
            model_name='cashcollector',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='amount_due_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer_address',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
