# Generated by Django 5.0.6 on 2024-07-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_collection', '0002_rename_frozen_at_cashcollector_frozen_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paid_to_manager',
            field=models.BooleanField(default=False),
        ),
    ]
